image: node:latest
cache:
  paths:
    - node_modules/
stages:
  - build_deploy
pages:
  stage: build_deploy
  before_script:
    - npm install
  script:
    - npm run build
    - rm -rf public
    - mkdir public
    - mv build/* public
    - echo "Created folder"
    - ls -Al public/*
  artifacts:
    paths:
      - public
  only:
    - master
